### ISSUE TITLE
Nothing happens except errors in eventlog

### ISSUE THREAD

**Issue by JustGuybrush** [AndrewBabbitt97/AuraConnect#123]
Hi,
Despite applying every troubleshooting steps, this doesn't work with my setup. 
Here are the application log and eventlog errors:
Thanks for your help.

2021-02-28T14:31:55.8116380+01:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Application started. Hosting environment: Production; Content root path: C:\Program Files (x86)\ASUS\AURACONNECT\
2021-02-28T14:31:56.8210787+01:00	INFO	[AuraConnect.Worker]	[Logging]	Initializing Aura Connect...

Log Name:      Application
Source:        .NET Runtime
Date:          28/02/2021 14:31:02
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      AsusMaxime
Description:
Application: AuraConnect.exe
CoreCLR Version: 4.700.20.6602
.NET Core Version: 3.1.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at AuraConnect.Program.Main(String[] args)

Log Name:      Application
Source:        Application Error
Date:          28/02/2021 14:31:02
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      AsusMaxime
Description:
Faulting application name: AuraConnect.exe, version: 1.1.0.0, time stamp: 0x5e222521
Faulting module name: KERNELBASE.dll, version: 10.0.19041.804, time stamp: 0xb610d74d
Exception code: 0xe0434352
Fault offset: 0x0012a8b2
Faulting process id: 0x3730
Faulting application start time: 0x01d70dd59ecec626
Faulting application path: C:\Program Files (x86)\ASUS\AURACONNECT\AuraConnect.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 3a3c4ca4-2f53-4b82-9e30-38de4cbc8312
Faulting package full name: 
Faulting package-relative application ID:

**Comment by AndrewBabbitt97** [comment]
AuraConnect has been archived, please move onto the replacement ChromaControl: https://github.com/ChromaControl/ChromaControl
